### ISSUE TITLE
SelfPAD_eval.py is failing

### ISSUE THREAD

**Issue by lukatop** [AstraZeneca/SelfPAD#1]
Hello, thanks for the good tool. I had some issues with installing dependencies, but made it work with Docker. Here is a Dockerfile.txt (extension added so upload is allowed) if someone finds it useful to build a tool in a container environment like Docker. 

However, when I ran selfpad_eval.py to evaluate humanness I am getting this error: 
```
Building the models for training and evaluation in SubTab framework...
Traceback (most recent call last):
  File "/opt/SelfPAD/selfpad_eval.py", line 250, in <module>
    main()
  File "/opt/SelfPAD/selfpad_eval.py", line 224, in main
    f1, recall, prec, auc, acc, pr_auc = eval(data_loader, config=config)
  File "/opt/SelfPAD/selfpad_eval.py", line 45, in eval
    model = PADFintune(config)
  File "/opt/SelfPAD/src/selfpad_humanness.py", line 47, in __init__
    self.set_autoencoder()
  File "/opt/SelfPAD/src/selfpad_humanness.py", line 53, in set_autoencoder
    self.transformer = PADFT(
  File "/opt/SelfPAD/utils_finetune/model_utils.py", line 49, in __init__
    self.transformer = SelfPAD.load_from_checkpoint(
  File "/usr/local/lib/python3.9/site-packages/pytorch_lightning/utilities/model_helpers.py", line 100, in wrapper
    return self.method(cls, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pytorch_lightning/core/module.py", line 1561, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/usr/local/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 61, in _load_from_checkpoint
    checkpoint = pl_load(checkpoint_path, map_location=map_location)
  File "/usr/local/lib/python3.9/site-packages/lightning_fabric/utilities/cloud_io.py", line 55, in _load
    with fs.open(path_or_url, "rb") as f:
  File "/usr/local/lib/python3.9/site-packages/fsspec/spec.py", line 1293, in open
    f = self._open(
  File "/usr/local/lib/python3.9/site-packages/fsspec/implementations/local.py", line 184, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/fsspec/implementations/local.py", line 306, in __init__
    self._open()
  File "/usr/local/lib/python3.9/site-packages/fsspec/implementations/local.py", line 311, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/SelfPAD/results/pretraining/training/model/pretrained_model.ckpt'
```

Input file I've used for testing is attached below. And this is the command line I've used: 
`python3 /opt/SelfPAD/selfpad_eval.py --evaluate therapeutic_ABs.selfpad_input`

Can you help me figure out what the issue is? 

[therapeutic_ABs.selfpad_input.csv](https://github.com/AstraZeneca/SelfPAD/files/14208379/therapeutic_ABs.selfpad_input.csv) 
[Dockerfile.txt](https://github.com/AstraZeneca/SelfPAD/files/14208357/Dockerfile.txt)

**Comment by talipucar** [comment]
Hi Luka,

This error is due to the fact that the repo does not include the pre-trained model weights. Since we use proprietary data to train the models, there is no plan to share the model weights. However, you can use the source code to train your own models  using publicly available datasets by framing the problem in the way we framed it in the paper. I will close the issue, but please feel free to re-open it if you have any other question(s).
